# Generated by Django 5.1 on 2024-11-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userspotifydata_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspotifydata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='top_artists',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='top_genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='wrap_name',
            field=models.CharField(max_length=100),
        ),
    ]
