# Generated by Django 5.1 on 2024-11-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userspotifydata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspotifydata',
            name='top_artists',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='top_genres',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
