# Generated by Django 5.1 on 2024-11-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userspotifydata_top_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspotifydata',
            name='top_artists',
        ),
        migrations.RemoveField(
            model_name='userspotifydata',
            name='top_genres',
        ),
    ]
