# Generated by Django 5.1 on 2024-11-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userspotifydata_top_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspotifydata',
            name='top_tracks',
        ),
        migrations.AddField(
            model_name='userspotifydata',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01T00:00:00Z'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spotify_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='accounts.userspotifydata')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spotify_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='accounts.userspotifydata')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('spotify_url', models.URLField()),
                ('spotify_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='accounts.userspotifydata')),
            ],
        ),
    ]
