# Generated by Django 5.1 on 2024-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userspotifydata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspotifydata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='wrap_name',
            field=models.CharField(max_length=255),
        ),
    ]
