# Generated by Django 5.1 on 2024-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userspotifydata_top_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='spotify_data',
        ),
        migrations.RemoveField(
            model_name='track',
            name='spotify_data',
        ),
        migrations.RemoveField(
            model_name='userspotifydata',
            name='top_artists',
        ),
        migrations.RemoveField(
            model_name='userspotifydata',
            name='top_genres',
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='top_tracks',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userspotifydata',
            name='wrap_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
