# Generated by Django 5.1 on 2024-11-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userspotifydata_term_alter_userspotifydata_wrap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspotifydata',
            name='top_genres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
