# Generated by Django 5.1.3 on 2024-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userspotifydata_top_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspotifydata',
            name='llm_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
